{% set name = "cptec-sazonal" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cptec-sazonal-{{ version }}.tar.gz
  sha256: 7050979faabe58032cb2e3c1049c1f1335d08c69581facf076c1207a7a02e931

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - pandas
    - xarray
    - requests
    - matplotlib-base
    - scipy
    - netcdf4

test:
  imports:
    - sazonal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sazonal.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/framework-CPTEC/Sazonal
  doc_url: https://github.com/framework-CPTEC/Sazonal
  summary: Módulo para distribuição do Modelo Sazonal do CPTEC.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - framework-CPTEC
